project_root_windows: "D:/Martina/REPOS/airfoil_OF_ML_project/airfoil-surrogate-OF-project"
template_case_windows: "D:/Martina/REPOS/airfoil_OF_ML_project/airfoil-surrogate-OF-project/templates/openfoam_base_case"
generated_profiles_windows: "D:/Martina/REPOS/airfoil_OF_ML_project/airfoil-surrogate-OF-project/geometry/generated_profiles"
sampling_table_windows: "D:/Martina/REPOS/airfoil_OF_ML_project/airfoil-surrogate-OF-project/geometry/generated_profiles/airfoil_sampling_table.csv"
openfoam_run_root_windows: "D:/Martina/REPOS/airfoil_OF_ML_project/airfoil-surrogate-OF-project/run/airfoil_surrogate_cases"
openfoam_bash_windows: "C:/OpenFOAM/20.09/cygwin64/bin/bash.exe"
openfoam_case_sim_windows: "C:/OpenFOAM/20.09/test_martina-dev/run/airfoil_surrogate_cases"