project_root_windows: "C:/Users/martina/airfoil_surrogate_OF_project"
template_case_windows: "C:/Users/martina/airfoil_surrogate_OF_project/templates/openfoam_base_case"
generated_profiles_windows: "C:/Users/martina/airfoil_surrogate_OF_project/geometry/generated_profiles"
sampling_table_windows: "C:/Users/martina/airfoil_surrogate_OF_project/geometry/generated_profiles/airfoil_sampling_table.csv"
openfoam_run_root_windows: "C:/OpenFOAM/20.09/martina-dev/run/airfoil_surrogate_cases"